# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
r:
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - release
  - devel
  
cache: packages
sudo: required
use_devtools: true

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:ubuntugis/ppa'
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev
      - libgsl0-dev
      - bwidget
      - gcc

r_packages:
  - covr

install:
  - Rscript -e 'devtools::install_deps(dep = T)'


script:
  - R CMD build .
  - R CMD check *tar.gz

after_success:
  - tar -C .. --xf $PKG_TARBALL
  - Rscript -e 'covr::codecov()'
