# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
r:
  - oldrel
  - release
  - devel
  
cache: packages
sudo: required

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:ubuntugis/ppa'
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev
      - libgsl0-dev
      - bwidget
      - gcc

r_packages:
  - covr

script:
  - R CMD build .

after_success:
  - tar -C .. --xf $PKG_TARBALL
