context("test-pops")

test_that("Model stops if files don't exist or aren't the correct extension", {
  expect_equal(pops(infected_file = "", host_file =  system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file =  system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS")), "Infected file does not exist")
  expect_equal(pops(infected_file =  system.file("extdata", "simple2x2", "infected.csv", package = "PoPS"), host_file =  system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file =  system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS")), "Infected file is not one of '.grd', '.tif', '.img'")
  expect_equal(pops(infected_file =  system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = "", total_plants_file =  system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS")), "Host file does not exist")
  expect_equal(pops(infected_file =  system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file =  system.file("extdata", "simple2x2", "infected.csv", package = "PoPS"), total_plants_file =  system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS")), "Host file is not one of '.grd', '.tif', '.img'")
  expect_equal(pops(infected_file =  system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file =  system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = ""), "Total plants file does not exist")
  expect_equal(pops(infected_file =  system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file =  system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file =  system.file("extdata", "simple2x2", "infected.csv", package = "PoPS")), "Total plants file is not one of '.grd', '.tif', '.img'")
  expect_equal(pops(infected_file =  system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file =  system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file =  system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), use_lethal_temperature = TRUE, temperature_file = ""), "Temperature file does not exist")
  expect_equal(pops(infected_file =  system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file =  system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file =  system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), use_lethal_temperature = TRUE, temperature_file =  system.file("extdata", "simple2x2", "infected.csv", package = "PoPS")), "Temperature file is not one of '.grd', '.tif', '.img'")
  expect_equal(pops(infected_file =  system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file =  system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file =  system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), temp = TRUE, temperature_coefficient_file = ""), "Temperature coefficient file does not exist")
  expect_equal(pops(infected_file =  system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file =  system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file =  system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), temp = TRUE, temperature_coefficient_file =  system.file("extdata", "simple2x2", "infected.csv", package = "PoPS")), "Temperature coefficient file is not one of '.grd', '.tif', '.img'")
  expect_equal(pops(infected_file =  system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file =  system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file =  system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), precip = TRUE, precipitation_coefficient_file = ""), "Precipitation coefficient file does not exist")
  expect_equal(pops(infected_file =  system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file =  system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file =  system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), precip = TRUE, precipitation_coefficient_file =  system.file("extdata", "simple2x2", "infected.csv", package = "PoPS")), "Precipitation coefficient file is not one of '.grd', '.tif', '.img'")

})

test_that("Model stops if parameters are of the wrong type and/or dimension", {
  expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), time_step = "two"), "Time step must be one of 'week', 'month' or 'day'")
  expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), end_time = "two"), "End time and/or start time not of type numeric and/or in format YYYY")
  expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), end_time = 156), "End time and/or start time not of type numeric and/or in format YYYY")
  expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), start_time = "five"), "End time and/or start time not of type numeric and/or in format YYYY")
  expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), start_time = 19), "End time and/or start time not of type numeric and/or in format YYYY")

})

test_that("Input raster resolutions, extents, and crs all match", {
  expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple5x5", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS")), "Extents of input rasters do not match. Ensure that all of your input rasters have the same extent")
  expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple5x5", "total_plants.tif", package = "PoPS")), "Extents of input rasters do not match. Ensure that all of your input rasters have the same extent")
  expect_equal(pops(infected_file = system.file("extdata", "simple5x5", "total_plants.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS")), "Extents of input rasters do not match. Ensure that all of your input rasters have the same extent")
  expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), use_lethal_temperature = TRUE, temperature_file = system.file("extdata", "simple2x2", "critical_temp_diff_extent.tif", package = "PoPS")), "Extents of input rasters do not match. Ensure that all of your input rasters have the same extent")
  expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), temp = TRUE, temperature_coefficient_file = system.file("extdata", "simple2x2", "critical_temp_diff_extent.tif", package = "PoPS")), "Extents of input rasters do not match. Ensure that all of your input rasters have the same extent")
  expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), precip = TRUE, precipitation_coefficient_file = system.file("extdata", "simple2x2", "critical_temp_diff_extent.tif", package = "PoPS")), "Extents of input rasters do not match. Ensure that all of your input rasters have the same extent")
  expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), temp = TRUE, temperature_coefficient_file = system.file("extdata", "simple2x2", "critical_temp.tif", package = "PoPS"), precip = TRUE, precipitation_coefficient_file = system.file("extdata", "simple2x2", "critical_temp_diff_extent.tif", package = "PoPS")), "Extents of input rasters do not match. Ensure that all of your input rasters have the same extent")

  expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants_diff_res.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS")), "Resolution of input rasters do not match. Ensure that all of your input rasters have the same resolution")
  expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants_diff_xres.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS")), "Resolution of input rasters do not match. Ensure that all of your input rasters have the same resolution")
  expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants_diff_yres.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS")), "Resolution of input rasters do not match. Ensure that all of your input rasters have the same resolution")
  expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants_diff_res.tif", package = "PoPS")), "Resolution of input rasters do not match. Ensure that all of your input rasters have the same resolution")
  expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants_diff_xres.tif", package = "PoPS")), "Resolution of input rasters do not match. Ensure that all of your input rasters have the same resolution")
  expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants_diff_yres.tif", package = "PoPS")), "Resolution of input rasters do not match. Ensure that all of your input rasters have the same resolution")
  expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "total_plants_diff_res.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS")), "Resolution of input rasters do not match. Ensure that all of your input rasters have the same resolution")
  expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "total_plants_diff_xres.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS")), "Resolution of input rasters do not match. Ensure that all of your input rasters have the same resolution")
  expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "total_plants_diff_yres.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS")), "Resolution of input rasters do not match. Ensure that all of your input rasters have the same resolution")
  expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), use_lethal_temperature = TRUE, temperature_file = system.file("extdata", "simple2x2", "critical_temp_diff_res.tif", package = "PoPS")), "Resolution of input rasters do not match. Ensure that all of your input rasters have the same resolution")
  expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), use_lethal_temperature = TRUE, temperature_file = system.file("extdata", "simple2x2", "critical_temp_diff_xres.tif", package = "PoPS")), "Resolution of input rasters do not match. Ensure that all of your input rasters have the same resolution")
  expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), use_lethal_temperature = TRUE, temperature_file = system.file("extdata", "simple2x2", "critical_temp_diff_yres.tif", package = "PoPS")), "Resolution of input rasters do not match. Ensure that all of your input rasters have the same resolution")
  expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), temp = TRUE, temperature_coefficient_file = system.file("extdata", "simple2x2", "critical_temp_diff_res.tif", package = "PoPS")), "Resolution of input rasters do not match. Ensure that all of your input rasters have the same resolution")
  expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), temp  = TRUE, temperature_coefficient_file = system.file("extdata", "simple2x2", "critical_temp_diff_xres.tif", package = "PoPS")), "Resolution of input rasters do not match. Ensure that all of your input rasters have the same resolution")
  expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), temp = TRUE, temperature_coefficient_file = system.file("extdata", "simple2x2", "critical_temp_diff_yres.tif", package = "PoPS")), "Resolution of input rasters do not match. Ensure that all of your input rasters have the same resolution")
  expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), precip = TRUE, precipitation_coefficient_file = system.file("extdata", "simple2x2", "critical_temp_diff_res.tif", package = "PoPS")), "Resolution of input rasters do not match. Ensure that all of your input rasters have the same resolution")
  expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), precip  = TRUE, precipitation_coefficient_file = system.file("extdata", "simple2x2", "critical_temp_diff_xres.tif", package = "PoPS")), "Resolution of input rasters do not match. Ensure that all of your input rasters have the same resolution")
  expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), precip = TRUE, precipitation_coefficient_file = system.file("extdata", "simple2x2", "critical_temp_diff_yres.tif", package = "PoPS")), "Resolution of input rasters do not match. Ensure that all of your input rasters have the same resolution")
  expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), temp = TRUE, temperature_coefficient_file = system.file("extdata", "simple2x2", "critical_temp.tif", package = "PoPS"), precip = TRUE, precipitation_coefficient_file = system.file("extdata", "simple2x2", "critical_temp_diff_res.tif", package = "PoPS")), "Resolution of input rasters do not match. Ensure that all of your input rasters have the same resolution")
  expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), temp = TRUE, temperature_coefficient_file = system.file("extdata", "simple2x2", "critical_temp.tif", package = "PoPS"), precip = TRUE, precipitation_coefficient_file = system.file("extdata", "simple2x2", "critical_temp_diff_xres.tif", package = "PoPS")), "Resolution of input rasters do not match. Ensure that all of your input rasters have the same resolution")
  expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), temp = TRUE, temperature_coefficient_file = system.file("extdata", "simple2x2", "critical_temp.tif", package = "PoPS"), precip = TRUE, precipitation_coefficient_file = system.file("extdata", "simple2x2", "critical_temp_diff_yres.tif", package = "PoPS")), "Resolution of input rasters do not match. Ensure that all of your input rasters have the same resolution")

  expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants_with_crs.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS")), "Coordinate reference system (crs) of input rasters do not match. Ensure that all of your input rasters have the same crs")
  expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants_with_crs.tif", package = "PoPS")), "Coordinate reference system (crs) of input rasters do not match. Ensure that all of your input rasters have the same crs")
  expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "total_plants_with_crs.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS")), "Coordinate reference system (crs) of input rasters do not match. Ensure that all of your input rasters have the same crs")
  expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), use_lethal_temperature = TRUE, temperature_file = system.file("extdata", "simple2x2", "critical_temp_diff_crs.tif", package = "PoPS")), "Coordinate reference system (crs) of input rasters do not match. Ensure that all of your input rasters have the same crs")
  expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), temp = TRUE, temperature_coefficient_file = system.file("extdata", "simple2x2", "critical_temp_diff_crs.tif", package = "PoPS")), "Coordinate reference system (crs) of input rasters do not match. Ensure that all of your input rasters have the same crs")
  expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), precip = TRUE, precipitation_coefficient_file = system.file("extdata", "simple2x2", "critical_temp_diff_crs.tif", package = "PoPS")), "Coordinate reference system (crs) of input rasters do not match. Ensure that all of your input rasters have the same crs")
  expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), temp = TRUE, temperature_coefficient_file = system.file("extdata", "simple2x2", "critical_temp.tif", package = "PoPS"), precip = TRUE, precipitation_coefficient_file = system.file("extdata", "simple2x2", "critical_temp_diff_crs.tif", package = "PoPS")), "Coordinate reference system (crs) of input rasters do not match. Ensure that all of your input rasters have the same crs")

})

test_that("Infected results return initial infected if reproductive rate is set to 0", {
  expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 0.0)$infected_vector[[1]], raster::as.matrix(raster::raster(system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"))))
  expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), use_lethal_temperature = TRUE, temperature_file = system.file("extdata", "simple2x2", "critical_temp.tif", package = "PoPS"), reproductive_rate = 0.0)$infected_vector[[1]], raster::as.matrix(raster::raster(system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"))))
  expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 0.0, temp = TRUE, temperature_coefficient_file = system.file("extdata", "simple2x2", "temperature_coefficient.tif", package = "PoPS"))[[1]][[1]], raster::as.matrix(raster::raster(system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"))))
  expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 0.0, precip = TRUE, precipitation_coefficient_file = system.file("extdata", "simple2x2", "temperature_coefficient.tif", package = "PoPS"))[[1]][[1]], raster::as.matrix(raster::raster(system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"))))
  expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 0.0, temp = TRUE, temperature_coefficient_file = system.file("extdata", "simple2x2", "temperature_coefficient.tif", package = "PoPS"), precip = TRUE, precipitation_coefficient_file = system.file("extdata", "simple2x2", "temperature_coefficient.tif", package = "PoPS"))[[1]][[1]], raster::as.matrix(raster::raster(system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"))))
  expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 0.0, use_lethal_temperature = TRUE, temperature_file = system.file("extdata", "simple2x2", "critical_temp.tif", package = "PoPS"), temp = TRUE, temperature_coefficient_file = system.file("extdata", "simple2x2", "temperature_coefficient.tif", package = "PoPS"), precip = TRUE, precipitation_coefficient_file = system.file("extdata", "simple2x2", "temperature_coefficient.tif", package = "PoPS"))[[1]][[1]], raster::as.matrix(raster::raster(system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"))))

  # expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 0.0, temp = TRUE, temperature_coefficient_file = system.file("extdata", "simple2x2", "temperature_coefficient_weeks.tif", package = "PoPS"), time_step = "week")[[1]][[1]], raster::as.matrix(raster::raster(system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"))))
  # expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 0.0, precip = TRUE, precipitation_coefficient_file = system.file("extdata", "simple2x2", "temperature_coefficient_weeks.tif", package = "PoPS"), time_step = "week")[[1]][[1]], raster::as.matrix(raster::raster(system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"))))
  # expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 0.0, temp = TRUE, temperature_coefficient_file = system.file("extdata", "simple2x2", "temperature_coefficient_weeks.tif", package = "PoPS"), precip = TRUE, precipitation_coefficient_file = system.file("extdata", "simple2x2", "temperature_coefficient_weeks.tif", package = "PoPS"), time_step = "week")[[1]][[1]], raster::as.matrix(raster::raster(system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"))))
  # expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 0.0, use_lethal_temperature = TRUE, temperature_file = system.file("extdata", "simple2x2", "critical_temp.tif", package = "PoPS"), temp = TRUE, temperature_coefficient_file = system.file("extdata", "simple2x2", "temperature_coefficient_weeks.tif", package = "PoPS"), precip = TRUE, precipitation_coefficient_file = system.file("extdata", "simple2x2", "temperature_coefficient_weeks.tif", package = "PoPS"), time_step = "week")[[1]][[1]], raster::as.matrix(raster::raster(system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"))))
  # 
  # expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 0.0, temp = TRUE, temperature_coefficient_file = system.file("extdata", "simple2x2", "temperature_coefficient_days.tif", package = "PoPS"))[[1]][[1]], raster::as.matrix(raster::raster(system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), time_step = "day")))
  # expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 0.0, precip = TRUE, precipitation_coefficient_file = system.file("extdata", "simple2x2", "temperature_coefficient_days.tif", package = "PoPS"))[[1]][[1]], raster::as.matrix(raster::raster(system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), time_step = "day")))
  # expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 0.0, temp = TRUE, temperature_coefficient_file = system.file("extdata", "simple2x2", "temperature_coefficient_days.tif", package = "PoPS"), precip = TRUE, precipitation_coefficient_file = system.file("extdata", "simple2x2", "temperature_coefficient_days.tif", package = "PoPS"), time_step = "day")[[1]][[1]], raster::as.matrix(raster::raster(system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"))))
  # expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 0.0, use_lethal_temperature = TRUE, temperature_file = system.file("extdata", "simple2x2", "critical_temp.tif", package = "PoPS"), temp = TRUE, temperature_coefficient_file = system.file("extdata", "simple2x2", "temperature_coefficient_days.tif", package = "PoPS"), precip = TRUE, precipitation_coefficient_file = system.file("extdata", "simple2x2", "temperature_coefficient_days.tif", package = "PoPS"), time_step = "day")[[1]][[1]], raster::as.matrix(raster::raster(system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"))))

})

test_that("Infected results returns all 0's if minimum temp drops below lethal temperature", {
  expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), use_lethal_temperature = TRUE, temperature_file = system.file("extdata", "simple2x2", "critical_temp_all_below_threshold.tif", package = "PoPS"))$infected_vector[[1]], matrix(0,ncol = 2, nrow = 2))
  expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), use_lethal_temperature = TRUE, temperature_file = system.file("extdata", "simple2x2", "critical_temp_all_below_threshold.tif", package = "PoPS"), precip = TRUE, precipitation_coefficient_file = system.file("extdata", "simple2x2", "temperature_coefficient.tif", package = "PoPS"))$infected_vector[[1]], matrix(0,ncol = 2, nrow = 2))
  expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), use_lethal_temperature = TRUE, temperature_file = system.file("extdata", "simple2x2", "critical_temp_all_below_threshold.tif", package = "PoPS"), temp = TRUE, temperature_coefficient_file = system.file("extdata", "simple2x2", "temperature_coefficient.tif", package = "PoPS"))$infected_vector[[1]], matrix(0,ncol = 2, nrow = 2))
  expect_equal(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), use_lethal_temperature = TRUE, temperature_file = system.file("extdata", "simple2x2", "critical_temp_all_below_threshold.tif", package = "PoPS"), temp = TRUE, temperature_coefficient_file = system.file("extdata", "simple2x2", "temperature_coefficient.tif", package = "PoPS"), precip = TRUE, precipitation_coefficient_file = system.file("extdata", "simple2x2", "temperature_coefficient.tif", package = "PoPS"))$infected_vector[[1]], matrix(0,ncol = 2, nrow = 2))

})

test_that("Infected results are greater than initial infected", {
  expect_equal(all(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"))[[1]][[1]] >= raster::as.matrix(raster::raster(system.file("extdata", "simple2x2", "infected.tif", package = "PoPS")))), TRUE)
  expect_equal(all(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants_host_greater_than_infected.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"))[[1]][[1]] >= raster::as.matrix(raster::raster(system.file("extdata", "simple2x2", "infected.tif", package = "PoPS")))), TRUE)

})

test_that("Susceptibles are never negative", {
  expect_equal(all(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 0.7)[[2]][[1]] >= matrix(0, ncol = 2, nrow = 2)), TRUE)
  expect_equal(all(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 0.7)[[2]][[2]] >= matrix(0, ncol = 2, nrow = 2)), TRUE)
  expect_equal(all(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 0.7)[[2]][[3]] >= matrix(0, ncol = 2, nrow = 2)), TRUE)

  expect_equal(all(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants_host_greater_than_infected.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 1.0)[[2]][[1]] >= matrix(0, ncol = 2, nrow = 2)), TRUE)
  expect_equal(all(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants_host_greater_than_infected.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 1.0)[[2]][[2]] >= matrix(0, ncol = 2, nrow = 2)), TRUE)
  expect_equal(all(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants_host_greater_than_infected.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 1.0)[[2]][[3]] >= matrix(0, ncol = 2, nrow = 2)), TRUE)

})

test_that("Infected results with weather are less than those without weather", {
  expect_equal(all(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 0.8)[[1]][[1]] >= pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), temp = TRUE, temperature_coefficient_file = system.file("extdata", "simple2x2", "temperature_coefficient.tif", package = "PoPS"), reproductive_rate = 0.8)[[1]][[1]]), TRUE)
  expect_equal(all(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 0.8)[[1]][[2]] >= pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), temp = TRUE, temperature_coefficient_file = system.file("extdata", "simple2x2", "temperature_coefficient.tif", package = "PoPS"), reproductive_rate = 0.8)[[1]][[2]]), TRUE)
  expect_equal(all(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 0.8)[[1]][[3]] >= pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), temp = TRUE, temperature_coefficient_file = system.file("extdata", "simple2x2", "temperature_coefficient.tif", package = "PoPS"), reproductive_rate = 0.8)[[1]][[3]]), TRUE)

  expect_equal(all(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 0.8)[[1]][[1]] >= pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), precip = TRUE, precipitation_coefficient_file = system.file("extdata", "simple2x2", "temperature_coefficient.tif", package = "PoPS"), reproductive_rate = 0.8)[[1]][[1]]), TRUE)
  expect_equal(all(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 0.8)[[1]][[2]] >= pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), precip = TRUE, precipitation_coefficient_file = system.file("extdata", "simple2x2", "temperature_coefficient.tif", package = "PoPS"), reproductive_rate = 0.8)[[1]][[2]]), TRUE)
  expect_equal(all(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 0.8)[[1]][[3]] >= pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), precip = TRUE, precipitation_coefficient_file = system.file("extdata", "simple2x2", "temperature_coefficient.tif", package = "PoPS"), reproductive_rate = 0.8)[[1]][[3]]), TRUE)

  expect_equal(all(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 0.9)[[1]][[1]] >= pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), temp = TRUE, temperature_coefficient_file = system.file("extdata", "simple2x2", "temperature_coefficient.tif", package = "PoPS"), precip = TRUE, precipitation_coefficient_file = system.file("extdata", "simple2x2", "temperature_coefficient.tif", package = "PoPS"), reproductive_rate = 0.9)[[1]][[1]]), TRUE)
  expect_equal(all(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 0.9)[[1]][[2]] >= pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), temp = TRUE, temperature_coefficient_file = system.file("extdata", "simple2x2", "temperature_coefficient.tif", package = "PoPS"), precip = TRUE, precipitation_coefficient_file = system.file("extdata", "simple2x2", "temperature_coefficient.tif", package = "PoPS"), reproductive_rate = 0.9)[[1]][[2]]), TRUE)
  expect_equal(all(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 0.9)[[1]][[3]] >= pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), temp = TRUE, temperature_coefficient_file = system.file("extdata", "simple2x2", "temperature_coefficient.tif", package = "PoPS"), precip = TRUE, precipitation_coefficient_file = system.file("extdata", "simple2x2", "temperature_coefficient.tif", package = "PoPS"), reproductive_rate = 0.9)[[1]][[3]]), TRUE)

})

test_that("Infected results are greater with same parameters for weekly spread vs. monthly", {
  expect_equal(all(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 0.4, time_step = "week")[[1]][[1]] >= pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 0.4, time_step = "month")[[1]][[1]]), TRUE)
  expect_equal(all(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 0.4, time_step = "week")[[1]][[2]] >= pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 0.4, time_step = "month")[[1]][[2]]), TRUE)

})

test_that("Infected results are greater with same parameters for daily spread vs. monthly and weekly", {
  expect_equal(all(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 0.3, time_step = "day")[[1]][[1]] >= pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 0.3, time_step = "month")[[1]][[1]]), TRUE)
  expect_equal(all(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 0.3, time_step = "day")[[1]][[2]] >= pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 0.3, time_step = "month")[[1]][[2]]), TRUE)

  expect_equal(all(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 0.2, time_step = "day")[[1]][[1]] >= pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 0.2, time_step = "week")[[1]][[1]]), TRUE)
  expect_equal(all(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 0.2, time_step = "day")[[1]][[2]] >= pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 0.2, time_step = "week")[[1]][[2]]), TRUE)
  expect_equal(all(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 0.2, time_step = "day")[[1]][[3]] >= pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 0.2, time_step = "week")[[1]][[3]]), TRUE)

})

test_that("Infected results are greater with higher higher reproductive rate", {
  expect_equal(all(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 1.25, time_step = "month")[[1]][[1]] >= pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 0.75, time_step = "month")[[1]][[1]]), TRUE)
  expect_equal(all(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 1.25, time_step = "month")[[1]][[2]] >= pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 0.75, time_step = "month")[[1]][[2]]), TRUE)

  expect_equal(all(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 0.42, time_step = "week")[[1]][[1]] >= pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 0.24, time_step = "week")[[1]][[1]]), TRUE)
  expect_equal(all(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 0.42, time_step = "week")[[1]][[2]] >= pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 0.24, time_step = "week")[[1]][[2]]), TRUE)

  expect_equal(all(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 0.15, time_step = "day")[[1]][[1]] >= pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 0.1, time_step = "month")[[1]][[1]]), TRUE)
  expect_equal(all(pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 0.15, time_step = "day")[[1]][[2]] >= pops(infected_file = system.file("extdata", "simple2x2", "infected.tif", package = "PoPS"), host_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), total_plants_file = system.file("extdata", "simple2x2", "total_plants.tif", package = "PoPS"), reproductive_rate = 0.1, time_step = "month")[[1]][[2]]), TRUE)

})
