context("test-pops")

test_that("Model stops if files don't exist or aren't the correct extension", {
  expect_equal(pops(infected_file = "", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif"), "Infected file does not exist")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.csv", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif"), "Infected file is not one of '.grd', '.tif', '.img'")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif"), "Host file does not exist")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.csv", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif"), "Host file is not one of '.grd', '.tif', '.img'")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = ""), "Total plants file does not exist")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.csv"), "Total plants file is not one of '.grd', '.tif', '.img'")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", use_lethal_temperature = TRUE, temperature_file = ""), "Temperature file does not exist")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", use_lethal_temperature = TRUE, temperature_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.csv"), "Temperature file is not one of '.grd', '.tif', '.img'")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", temp = TRUE, temperature_coefficient_file = ""), "Temperature coefficient file does not exist")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", temp = TRUE, temperature_coefficient_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.csv"), "Temperature coefficient file is not one of '.grd', '.tif', '.img'")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", precip = TRUE, precipitation_coefficient_file = ""), "Precipitation coefficient file does not exist")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", precip = TRUE, precipitation_coefficient_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.csv"), "Precipitation coefficient file is not one of '.grd', '.tif', '.img'")
  
})

test_that("Model stops if parameters are of the wrong type and/or dimension", {
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", time_step = "two"), "Time step must be one of 'week', 'month' or 'day'")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", end_time = "two"), "End time and/or start time not of type numeric and/or in format YYYY")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", end_time = 156), "End time and/or start time not of type numeric and/or in format YYYY")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", start_time = "five"), "End time and/or start time not of type numeric and/or in format YYYY")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", start_time = 19), "End time and/or start time not of type numeric and/or in format YYYY")
  
})

test_that("Input raster resolutions, extents, and crs all match", {
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple5x5/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif"), "Extents of input rasters do not match. Ensure that all of your input rasters have the same extent")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple5x5/total_plants.tif"), "Extents of input rasters do not match. Ensure that all of your input rasters have the same extent")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple5x5/total_plants.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif"), "Extents of input rasters do not match. Ensure that all of your input rasters have the same extent")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", use_lethal_temperature = TRUE, temperature_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/critical_temp_diff_extent.tif"), "Extents of input rasters do not match. Ensure that all of your input rasters have the same extent")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", temp = TRUE, temperature_coefficient_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/critical_temp_diff_extent.tif"), "Extents of input rasters do not match. Ensure that all of your input rasters have the same extent")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", precip = TRUE, precipitation_coefficient_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/critical_temp_diff_extent.tif"), "Extents of input rasters do not match. Ensure that all of your input rasters have the same extent")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", temp = TRUE, temperature_coefficient_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/critical_temp.tif", precip = TRUE, precipitation_coefficient_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/critical_temp_diff_extent.tif"), "Extents of input rasters do not match. Ensure that all of your input rasters have the same extent")
  
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants_diff_res.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif"), "Resolution of input rasters do not match. Ensure that all of your input rasters have the same resolution")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants_diff_xres.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif"), "Resolution of input rasters do not match. Ensure that all of your input rasters have the same resolution")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants_diff_yres.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif"), "Resolution of input rasters do not match. Ensure that all of your input rasters have the same resolution")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants_diff_res.tif"), "Resolution of input rasters do not match. Ensure that all of your input rasters have the same resolution")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants_diff_xres.tif"), "Resolution of input rasters do not match. Ensure that all of your input rasters have the same resolution")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants_diff_yres.tif"), "Resolution of input rasters do not match. Ensure that all of your input rasters have the same resolution")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants_diff_yres.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif"), "Resolution of input rasters do not match. Ensure that all of your input rasters have the same resolution")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants_diff_yres.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif"), "Resolution of input rasters do not match. Ensure that all of your input rasters have the same resolution")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants_diff_yres.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif"), "Resolution of input rasters do not match. Ensure that all of your input rasters have the same resolution")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", use_lethal_temperature = TRUE, temperature_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/critical_temp_diff_res.tif"), "Resolution of input rasters do not match. Ensure that all of your input rasters have the same resolution")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", use_lethal_temperature = TRUE, temperature_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/critical_temp_diff_xres.tif"), "Resolution of input rasters do not match. Ensure that all of your input rasters have the same resolution")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", use_lethal_temperature = TRUE, temperature_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/critical_temp_diff_yres.tif"), "Resolution of input rasters do not match. Ensure that all of your input rasters have the same resolution")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", temp = TRUE, temperature_coefficient_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/critical_temp_diff_res.tif"), "Resolution of input rasters do not match. Ensure that all of your input rasters have the same resolution")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", temp  = TRUE, temperature_coefficient_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/critical_temp_diff_xres.tif"), "Resolution of input rasters do not match. Ensure that all of your input rasters have the same resolution")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", temp = TRUE, temperature_coefficient_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/critical_temp_diff_yres.tif"), "Resolution of input rasters do not match. Ensure that all of your input rasters have the same resolution")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", precip = TRUE, precipitation_coefficient_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/critical_temp_diff_res.tif"), "Resolution of input rasters do not match. Ensure that all of your input rasters have the same resolution")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", precip  = TRUE, precipitation_coefficient_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/critical_temp_diff_xres.tif"), "Resolution of input rasters do not match. Ensure that all of your input rasters have the same resolution")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", precip = TRUE, precipitation_coefficient_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/critical_temp_diff_yres.tif"), "Resolution of input rasters do not match. Ensure that all of your input rasters have the same resolution")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", temp = TRUE, temperature_coefficient_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/critical_temp.tif", precip = TRUE, precipitation_coefficient_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/critical_temp_diff_res.tif"), "Resolution of input rasters do not match. Ensure that all of your input rasters have the same resolution")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", temp  = TRUE, temperature_coefficient_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/critical_temp.tif", precip = TRUE, precipitation_coefficient_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/critical_temp_diff_res.tif"), "Resolution of input rasters do not match. Ensure that all of your input rasters have the same resolution")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", temp = TRUE, temperature_coefficient_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/critical_temp.tif", precip = TRUE, precipitation_coefficient_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/critical_temp_diff_res.tif"), "Resolution of input rasters do not match. Ensure that all of your input rasters have the same resolution")
  
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants_with_crs.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif"), "Coordinate reference system (crs) of input rasters do not match. Ensure that all of your input rasters have the same crs")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants_with_crs.tif"), "Coordinate reference system (crs) of input rasters do not match. Ensure that all of your input rasters have the same crs")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants_with_crs.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif"), "Coordinate reference system (crs) of input rasters do not match. Ensure that all of your input rasters have the same crs")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", use_lethal_temperature = TRUE, temperature_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/critical_temp_diff_crs.tif"), "Coordinate reference system (crs) of input rasters do not match. Ensure that all of your input rasters have the same crs")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", temp = TRUE, temperature_coefficient_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/critical_temp_diff_crs.tif"), "Coordinate reference system (crs) of input rasters do not match. Ensure that all of your input rasters have the same crs")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", precip = TRUE, precipitation_coefficient_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/critical_temp_diff_crs.tif"), "Coordinate reference system (crs) of input rasters do not match. Ensure that all of your input rasters have the same crs")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", temp = TRUE, temperature_coefficient_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/critical_temp.tif", precip = TRUE, precipitation_coefficient_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/critical_temp_diff_crs.tif"), "Coordinate reference system (crs) of input rasters do not match. Ensure that all of your input rasters have the same crs")
  
})

test_that("Infected results return initial infected if reproductive rate is set to 0", {
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", reproductive_rate = 0.0)$infected_vector[[1]], raster::as.matrix(raster::raster("C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif")))
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", use_lethal_temperature = TRUE, temperature_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/critical_temp.tif", reproductive_rate = 0.0)$infected_vector[[1]], raster::as.matrix(raster::raster("C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif")))
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", reproductive_rate = 0.0, temp = TRUE, temperature_coefficient_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/temperature_coefficient.tif")[[1]][[1]], raster::as.matrix(raster::raster("C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif")))
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", reproductive_rate = 0.0, precip = TRUE, precipitation_coefficient_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/temperature_coefficient.tif")[[1]][[1]], raster::as.matrix(raster::raster("C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif")))
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", reproductive_rate = 0.0, temp = TRUE, temperature_coefficient_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/temperature_coefficient.tif", precip = TRUE, precipitation_coefficient_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/temperature_coefficient.tif")[[1]][[1]], raster::as.matrix(raster::raster("C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif")))
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", reproductive_rate = 0.0, use_lethal_temperature = TRUE, temperature_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/critical_temp.tif", temp = TRUE, temperature_coefficient_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/temperature_coefficient.tif", precip = TRUE, precipitation_coefficient_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/temperature_coefficient.tif")[[1]][[1]], raster::as.matrix(raster::raster("C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif")))
  
  # expect_gte(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif")[[1]][[1]], raster::as.matrix(raster::raster("C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif")))

})