context("test-pops")

test_that("Model stops if files don't exist or aren't the correct extension", {
  expect_equal(pops(infected_file = "", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif"), "Infected file does not exist")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.csv", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif"), "Infected file is not one of '.grd', '.tif', '.img'")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif"), "Host file does not exist")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.csv", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif"), "Host file is not one of '.grd', '.tif', '.img'")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = ""), "Total plants file does not exist")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.csv"), "Total plants file is not one of '.grd', '.tif', '.img'")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", use_lethal_temperature = TRUE, temperature_file = ""), "Temperature file does not exist")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", use_lethal_temperature = TRUE, temperature_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.csv"), "Temperature file is not one of '.grd', '.tif', '.img'")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", temp = TRUE, temperature_coefficient_file = ""), "Temperature coefficient file does not exist")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", temp = TRUE, temperature_coefficient_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.csv"), "Temperature coefficient file is not one of '.grd', '.tif', '.img'")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", precip = TRUE, precipitation_coefficient_file = ""), "Precipitation coefficient file does not exist")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", precip = TRUE, precipitation_coefficient_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.csv"), "Precipitation coefficient file is not one of '.grd', '.tif', '.img'")
  
  })

test_that("Model stops if parameters are of the wrong type and/or dimension", {
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", time_step = "two"), "Time step must be one of 'week', 'month' or 'day'")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", end_time = "two"), "End time and/or start time not of type numeric and/or in format YYYY")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", end_time = 156), "End time and/or start time not of type numeric and/or in format YYYY")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", start_time = "five"), "End time and/or start time not of type numeric and/or in format YYYY")
  expect_equal(pops(infected_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/infected.tif", host_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", total_plants_file = "C:/Users/Chris/Desktop/rpops/data/simple2x2/total_plants.tif", start_time = 19), "End time and/or start time not of type numeric and/or in format YYYY")
  
  })
