# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pops_model <- function(random_seed, lethal_temperature, use_lethal_temperature, lethal_temperature_month, reproductive_rate, weather, short_distance_scale, infected, susceptible, mortality_tracker, total_plants, temperature, weather_coefficient, ew_res, ns_res, time_step, season_month_start = 1L, season_month_end = 12L, start_time = 2018, end_time = 2018, dispersal_kern = "cauchy", percent_short_distance_dispersal = 0.0, long_distance_scale = 0.0, wind_dir = "NONE", kappa = 0) {
    .Call(`_PoPS_pops_model`, random_seed, lethal_temperature, use_lethal_temperature, lethal_temperature_month, reproductive_rate, weather, short_distance_scale, infected, susceptible, mortality_tracker, total_plants, temperature, weather_coefficient, ew_res, ns_res, time_step, season_month_start, season_month_end, start_time, end_time, dispersal_kern, percent_short_distance_dispersal, long_distance_scale, wind_dir, kappa)
}

