# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' PoPS c++ model
#'
#' @inheritParams pops
#' @param weather Boolean that is true if weather is used
#' @param infected matrix of infected hosts
#' @param susceptible matrix of susceptible hosts
#' @param mortality_tracker matrix of 0's to track mortality per year
#' @param mortality matrix to track cumulative mortality
#' @param resistant matrix to track resistant population over time
#' @param total_plants  matrix of total plants
#' @param treatment_maps list of matrices where treatment or management has occurred in a given year
#' @param temperature vector of matrices of temperature values used to check against lethal temperature
#' @param weather_coefficient vector of matrices of weather coefficients
#' @param ew_res east and west resolution
#' @param ns_res north and south resolution
#' @param num_rows number of rows in the raster files
#' @param num_cols number of columns in the raster files
#' @param use_anthropogenic_kernel A boolean that turns on the use of the anthropogenic or long distance dispersal portion of the 2 scale dispersal kernel function
#'
#' @return list of vector matrices of infected and suceptible hosts per simulated year
#' @export
#' 
pops_model <- function(random_seed, use_lethal_temperature, lethal_temperature, lethal_temperature_month, infected, susceptible, total_plants, mortality_on, mortality_tracker, mortality, treatment_maps, treatment_dates, pesticide_duration, resistant, weather, temperature, weather_coefficient, ew_res, ns_res, num_rows, num_cols, time_step, reproductive_rate, mortality_rate = 0.0, mortality_time_lag = 2L, season_month_start = 1L, season_month_end = 12L, start_time = 2018, end_time = 2018, treatment_month = 12L, treatment_method = "ratio", natural_kernel_type = "cauchy", anthropogenic_kernel_type = "cauchy", use_anthropogenic_kernel = FALSE, percent_natural_dispersal = 0.0, natural_distance_scale = 21, anthropogenic_distance_scale = 0.0, natural_dir = "NONE", natural_kappa = 0, anthropogenic_dir = "NONE", anthropogenic_kappa = 0) {
    .Call(`_PoPS_pops_model`, random_seed, use_lethal_temperature, lethal_temperature, lethal_temperature_month, infected, susceptible, total_plants, mortality_on, mortality_tracker, mortality, treatment_maps, treatment_dates, pesticide_duration, resistant, weather, temperature, weather_coefficient, ew_res, ns_res, num_rows, num_cols, time_step, reproductive_rate, mortality_rate, mortality_time_lag, season_month_start, season_month_end, start_time, end_time, treatment_month, treatment_method, natural_kernel_type, anthropogenic_kernel_type, use_anthropogenic_kernel, percent_natural_dispersal, natural_distance_scale, anthropogenic_distance_scale, natural_dir, natural_kappa, anthropogenic_dir, anthropogenic_kappa)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_PoPS_RcppExport_registerCCallable', PACKAGE = 'PoPS')
})
